Investigate https://github.com/robolectric/robolectric/issues/3698 with @brettchabot
This updates the robolectric dependency to 4.3-beta-1, and adds `@LooperMode(LooperMide.Mode.PAUSED)`
annotations

That's a semantic version major release break already, but still results in a failure indicating something
not backwards-compatible somewhere:

```
mike@isabela:~/work/AnkiDroid/Anki-Android (robolectric43b1test *) % ./gradlew clean jacocoUnitTestReport

> Configure project :AnkiDroid
Signing not ready. Be sure to specify a signingConfig for Release

> Task :AnkiDroid:testDebugUnitTest

com.ichi2.anki.CardTemplateEditorTest > testDeleteTemplate FAILED
    java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.

        Caused by:
        org.junit.ComparisonFailure: model did not save? expected:<...pls":[{"name":"Card [2","ord":0],"qfmt":"{{Back}}","...> but was:<...pls":[{"name":"Card [1","ord":0,"qfmt":"{{Front}}","afmt":"{{FrontSide}}\n\n<hr id=answer>\n\n{{Back}}","did":null,"bqfmt":"","bafmt":"","bfont":"Arial","bsize":12},{"name":"Card 2","ord":1],"qfmt":"{{Back}}","...>
            at org.junit.Assert.assertEquals(Assert.java:115)
            at com.ichi2.anki.CardTemplateEditorTest.testDeleteTemplate(CardTemplateEditorTest.java:250)

com.ichi2.anki.CardTemplateEditorTest > testTemplateAdd FAILED
    java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.

        Caused by:
        org.junit.ComparisonFailure: model did not save? expected:<...:"Arial","bsize":12}[,{"name":"Card 2","ord":1,"qfmt":"{{Back}}","afmt":"{{FrontSide}}\n\n<hr id=answer>\n\n{{Front}}","did":null,"bqfmt":"","bafmt":"","bfont":"Arial","bsize":12}]],"tags":[],"id":155...> but was:<...:"Arial","bsize":12}[]],"tags":[],"id":155...>
            at org.junit.Assert.assertEquals(Assert.java:115)
            at com.ichi2.anki.CardTemplateEditorTest.testTemplateAdd(CardTemplateEditorTest.java:288)

com.ichi2.anki.CardTemplateEditorTest > testEditTemplateContents FAILED
    java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.

        Caused by:
        org.junit.ComparisonFailure: model did not save? expected:<...:0,"qfmt":"{{Front}}[!@#$%^&*TEST*&^%$#@!]","afmt":"{{FrontSid...> but was:<...:0,"qfmt":"{{Front}}[]","afmt":"{{FrontSid...>
            at org.junit.Assert.assertEquals(Assert.java:115)
            at com.ichi2.anki.CardTemplateEditorTest.testEditTemplateContents(CardTemplateEditorTest.java:138)

47 tests completed, 3 failed

```